FLUID-6598 Test with Node.js 14 and 15
fluid-project/stylelint-config-fluid pull request #4
Opened 2021-02-10 11:40 UTC by gtirloni

2021-02-10 12:32 UTC, greatislander requested changes
@gtirloni can you resolve the merge conflict in package-lock.json?

2021-04-16 07:58 UTC, the-t-in-rtf commented
@greatislander, can you cut a dev release?  I'd like to update Gio's pull against fluiid-lint-all with it and confirm that we can use npm@7 once the versions match.

2021-04-16 11:31 UTC, greatislander commented
@the-t-in-rtf you can test this with stylelint-config-fluid@0.3.0-dev.20210416.GH-4.

2021-04-16 11:31 UTC, greatislander approved these changes

2021-04-16 11:31 UTC, merged